import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col items-center justify-between p-24 max-w-5xl mx-auto">
          <h1 className="text-4xl font-bold text-center mb-4">CodeTalk</h1>
          {children}
          <span className="text-sm text-gray-500 mt-4">
            Made with ❤️ by <b>Ideas Locas - Discovery - CDO</b>
          </span>
        </div>
      </body>
    </html>
  )
}
